---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://webhook.gatsbyjs.com/hooks/data_source/ed64145f-a51e-4a2d-9b46-34c35f0b93b2
sections:
- type: document
  path: content/settings.json
  label: Ajustes
  match: "**/*"
- type: directory
  path: content/articles
  label: Artigos
  create: all
  match: "**/*"
- type: directory
  path: content/sections
  label: Seções
  create: all
  match: "**/*"
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/"
  working_dir: "/"
  instant_preview_command: gatsby develop -p
